FROM golang:1.26.3-alpine AS builder
WORKDIR /app
COPY go.mod ./

#COPY go.sum ./
RUN go mod download
COPY main.go .
RUN CGO_ENABLED=0 GOOS=linux go build -o backend main.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
RUN addgroup -S appgroup && adduser -S appuser -G appgroup -u 10001
WORKDIR /home/appuser
COPY --from=builder /app/backend .
RUN chown appuser:appgroup backend
USER 10001
EXPOSE 8080
CMD ["./backend"]
